import Footer from "@/components/Footer";
import IconProvider from "@/components/IconProvider";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <IconProvider>
          <Navbar />

          <div
            className="flex justify-between flex-col"
            style={{ height: "90vh" }}
          >
            {children}
            <Footer />
          </div>
        </IconProvider>
      </body>
    </html>
  );
}
